DROP PROCEDURE IF EXISTS INSERTAR_CLIENTE_VENDEDOR;
DROP PROCEDURE IF EXISTS ELIMINAR_CLIENTE_VENDEDOR;
DELIMITER $
CREATE PROCEDURE INSERTAR_CLIENTE_VENDEDOR(
	OUT _ID_CLIENTE_VENDEDOR INT,
    IN _ID_CLIENTE INT,
    IN _ID_VENDEDOR INT,
    IN _ACTIVE TINYINT(1))
BEGIN
INSERT INTO CLIENTE_VENDEDOR(ID_CLIENTE,ID_VENDEDOR,ACTIVE)
VALUES (_ID_CLIENTE,_ID_VENDEDOR,_ACTIVE);
SET _ID_CLIENTE_VENDEDOR = last_insert_id();
END$

CREATE PROCEDURE ELIMINAR_CLIENTE_VENDEDOR(
	IN _ID_CLIENTE_VENDEDOR INT)
BEGIN
UPDATE CLIENTE_VENDEDOR
SET ACTIVE = FALSE
WHERE ID_CLIENTE_VENDEDOR = _ID_CLIENTE_VENDEDOR;
END$