DELIMITER $
DROP PROCEDURE IF EXISTS INSERTAR_DATOS_GENERALES;
CREATE PROCEDURE INSERTAR_DATOS_GENERALES(
	OUT _ID_DATOS_GENERALES INT,
    IN _IGV FLOAT,
    IN _SUELDO_MINIMO FLOAT,
    IN _CORREO_EMPRESA VARCHAR(80),
    IN _CONTRASEÑA_EMPRESA VARCHAR(80),
    IN _FECHA DATE,
    IN _PLAZO_DE_PAGO INT,
    IN _ACTIVE BOOLEAN
)
BEGIN
INSERT INTO DATOS_GENERALES(IGV,SUELDO_MINIMO,CORREO_EMPRESA,CONTRASEÑA_EMPRESA,FECHA,PLAZO_DE_PAGO,ACTIVE)
VALUES (_IGV,_SUELDO_MINIMO,_CORREO_EMPRESA,_CONTRASEÑA_EMPRESA,_FECHA,_PLAZO_DE_PAGO,_ACTIVE);
SET _ID_DATOS_GENERALES = last_insert_id();
END$

DROP PROCEDURE IF EXISTS ENCONTRAR_DATOS_GENERALES_POR_FECHA;
CREATE PROCEDURE ENCONTRAR_DATOS_GENERALES_POR_FECHA(
	IN _FECHA DATE
)
BEGIN
SELECT * FROM DATOS_GENERALES
WHERE FECHA = _FECHA AND ACTIVE = TRUE;
END$