USE lp2;
DELIMITER $
DROP PROCEDURE IF EXISTS INSERTAR_EMPLEADO;

CREATE PROCEDURE INSERTAR_EMPLEADO(
	OUT _ID_EMPLEADO INT,
    IN _DNI_EMPLEADO VARCHAR(8),
    IN _NOMBRE_EMPLEADO VARCHAR(80),
    IN _APELLIDOS VARCHAR(80),
    IN _FECHA_NACIMIENTO DATE,
    IN _TELEFONO_EMPLEADO VARCHAR(10),
    IN _CORREO_EMPLEADO VARCHAR(80),
    IN _ESTADO_CIVIL ENUM('Soltero','Casado'),
    IN _SUELDO FLOAT,
    IN _ID_AREA INT,
    IN _FECHA_INGRESO DATE,
    IN _ACTIVE TINYINT(1)
)
BEGIN
INSERT INTO EMPLEADO(NOMBRE_EMPLEADO, APELLIDOS_EMPLEADO,DNI_EMPLEADO,FECHA_NACIMIENTO,TELEFONO_EMPLEADO,
CORREO_EMPLEADO,ESTADO_CIVIL,SUELDO,ID_AREA,FECHA_INGRESO,ACTIVE)
VALUES (_NOMBRE_EMPLEADO, _APELLIDOS,_DNI_EMPLEADO,_FECHA_NACIMIENTO,_TELEFONO_EMPLEADO,
_CORREO_EMPLEADO,_ESTADO_CIVIL,_SUELDO,_ID_AREA,_FECHA_INGRESO,_ACTIVE);
SET _ID_EMPLEADO = last_insert_id();
END$

DROP PROCEDURE IF EXISTS ACTUALIZAR_EMPLEADO;

CREATE PROCEDURE ACTUALIZAR_EMPLEADO(
	IN _ID_EMPLEADO INT,
    IN _DNI_EMPLEADO VARCHAR(8),
    IN _NOMBRE_EMPLEADO VARCHAR(80),
    IN _APELLIDOS VARCHAR(80),
    IN _FECHA_NACIMIENTO DATE,
    IN _TELEFONO_EMPLEADO VARCHAR(10),
    IN _CORREO_EMPLEADO VARCHAR(80),
    IN _ESTADO_CIVIL ENUM('Soltero','Casado'),
    IN _SUELDO FLOAT,
    IN _ID_AREA INT,
    IN _FECHA_INGRESO DATE)
BEGIN
UPDATE EMPLEADO
SET DNI_EMPLEADO = _DNI_EMPLEADO, NOMBRE_EMPLEADO = _NOMBRE_EMPLEADO, APELLIDOS = _APELLIDOS,
FECHA_NACIMIENTO = _FECHA_NACIMIENTO,TELEFONO_EMPLEADO = _TELEFONO_EMPLEADO,CORREO_EMPLEADO = _CORREO_EMPLEADO,
ESTADO_CIVIL = _ESTADO_CIVIL, SUELDO = _SUELDO, AREA = _ID_AREA, FECHA_INGRESO = _FECHA_INGRESO
WHERE ID_EMPLEADO = _ID_EMPLEADO;
END$

DROP PROCEDURE IF EXISTS ELIMINAR_EMPLEADO;
CREATE PROCEDURE ELIMINAR_EMPLEADO(
	IN _ID_EMPLEADO INT)
BEGIN
UPDATE EMPLEADO
SET ACTIVE = FALSE
WHERE ID_EMPLEADO = _ID_EMPLEADO;
END$

DROP PROCEDURE IF EXISTS LISTAR_EMPLEADO;
CREATE PROCEDURE LISTAR_EMPLEADO()
BEGIN
SELECT * FROM EMPLEADO
INNER JOIN AREA on EMPLEADO.ID_AREA = AREA.ID_AREA
WHERE EMPLEADO.ACTIVE = TRUE;
END$

DROP PROCEDURE IF EXISTS LISTAR_EMPLEADO_POR_AREA;
CREATE PROCEDURE LISTAR_EMPLEADO_POR_AREA(
	IN _ID_AREA INT)
BEGIN
SELECT * FROM EMPLEADO
INNER JOIN AREA ON EMPLEADO.ID_AREA = AREA.ID_AREA
WHERE EMPLEADO.ACTIVE = TRUE AND EMPLEADO.ID_AREA = _ID_AREA;
END$

