DROP PROCEDURE IF EXISTS INSERTAR_OBJETIVO_VENDEDOR;
DROP PROCEDURE IF EXISTS ACTUALIZAR_OBJETIVO_VENDEDOR;

DELIMITER $
CREATE PROCEDURE INSERTAR_OBJETIVO_VENDEDOR(
	OUT _ID_OBJETIVO_VENDEDOR INT,
    IN _ID_META_MENSUAL INT,
    IN _MONTO FLOAT,
    IN _COMISION FLOAT,
    IN _BONO FLOAT,
    IN _ID_VENDEDOR INT,
    IN _ACTIVE TINYINT(1))
BEGIN
INSERT INTO OBJETIVO_VENDEDOR(ID_META_MENSUAL,MONTO,COMISION,BONO,ID_VENDEDOR,ACTIVE)
VALUES(_ID_META_MENSUAL,_MONTO,_COMISION,_BONO,_ID_VENDEDOR,_ACTIVE);
SET _ID_OBJETIVO_VENDEDOR = last_insert_id();
END$

CREATE PROCEDURE ACTUALIZAR_OBJETIVO_VENDEDOR(
	IN _ID_OBJETIVO_VENDEDOR INT,
    IN _ID_META_MENSUAL INT,
    IN _MONTO FLOAT,
    IN _COMISION FLOAT,
    IN _BONO FLOAT)
BEGIN
UPDATE OBJETIVO_VENDEDOR
SET ID_META_MENSUAL = _ID_META_MENSUAL, MONTO = _MONTO, COMISION = _COMISION, BONO = _BONO;
END$