DROP PROCEDURE IF EXISTS INSERTAR_PEDIDO;
DROP PROCEDURE IF EXISTS ACTUALIZAR_PEDIDO;
DROP PROCEDURE IF EXISTS ELIMINAR_PEDIDO;
DROP PROCEDURE IF EXISTS LISTAR_PEDIDO_POR_VENDEDOR;
DROP PROCEDURE IF EXISTS LISTAR_PEDIDO_POR_CLIENTE;
DROP PROCEDURE IF EXISTS LISTAR_PEDIDO_POR_VENDEDOR_POR_FECHAS;
DROP PROCEDURE IF EXISTS LISTAR_PEDIDO_POR_ESTADO;
DELIMITER $
CREATE PROCEDURE INSERTAR_PEDIDO(
	OUT _ID_PEDIDO INT,
    IN _TOTAL_PEDIDO FLOAT,
    IN _ID_CLIENTE_VENDEDOR INT,
    IN _ESTADO_PEDIDO ENUM('Aceptado','Rechazado','Pendiente','Pagado'),
    IN _FECHA_REGISTRO DATE,
	IN _ACTIVE TINYINT(1))
BEGIN
INSERT INTO PEDIDO(TOTAL_PEDIDO,ID_CLIENTE_VENDEDOR,ESTADO_PEDIDO,FECHA_REGISTRO,ACTIVE)
VALUES(_TOTAL_PEDIDO,_ID_CLIENTE_VENDEDOR,_ESTADO_PEDIDO,_FECHA_REGISTRO,_ACTIVE);
SET _ID_PEDIDO = last_insert_id();
END$

CREATE PROCEDURE ACTUALIZAR_PEDIDO(
	IN _ID_PEDIDO INT,
    IN _TOTAL_PEDIDO FLOAT,
    IN _ESTADO_PEDIDO ENUM('Aceptado','Rechazado','Pendiente','Pagado'),
    IN _FECHA_REGISTRO DATE)
BEGIN
UPDATE PEDIDO
SET TOTAL_PEDIDO=_TOTAL_PEDIDO, ESTADO_PEDIDO = _ESTADO_PEDIDO, FECHA_REGISTRO = _FECHA_REGISTRO
WHERE ID_PEDIDO = _ID_PEDIDO;
END$

CREATE PROCEDURE ELIMINAR_PEDIDO(
	IN _ID_PEDIDO INT)
BEGIN
UPDATE PEDIDO
SET ACTIVE = FALSE
WHERE ID_PEDIDO = _ID_PEDIDO;
END$

CREATE PROCEDURE LISTAR_PEDIDO_POR_VENDEDOR(
	IN _ID_VENDEDOR INT)
BEGIN
SELECT * FROM PEDIDO,CLIENTE_VENDEDOR,CLIENTE	
WHERE CLIENTE_VENDEDOR.ID_VENDEDOR = _ID_VENDEDOR
AND PEDIDO.ID_CLIENTE_VENDEDOR = CLIENTE_VENDEDOR.ID_CLIENTE_VENDEDOR
AND CLIENTE.ID_CLIENTE = CLIENTE_VENDEDOR.ID_CLIENTE
AND ACTIVE = TRUE;
END$

CREATE PROCEDURE LISTAR_PEDIDO_POR_VENDEDOR_POR_FECHAS(
	IN _FECHA_INI DATE,
    IN _FECHA_FIN DATE,
	IN _ID_VENDEDOR INT)
BEGIN
SELECT * FROM PEDIDO,CLIENTE_VENDEDOR,CLIENTE	
WHERE CLIENTE_VENDEDOR.ID_VENDEDOR = _ID_VENDEDOR
AND PEDIDO.ID_CLIENTE_VENDEDOR = CLIENTE_VENDEDOR.ID_CLIENTE_VENDEDOR
AND CLIENTE.ID_CLIENTE = CLIENTE_VENDEDOR.ID_CLIENTE
AND PEDIDO.FECHA_REGISTRO BETWEEN _FECHA_INI AND _FECHA_FIN
AND ACTIVE = TRUE;
END$

CREATE PROCEDURE LISTAR_PEDIDO_POR_CLIENTE(
	IN _ID_CLIENTE INT)
BEGIN
SELECT * FROM PEDIDO,CLIENTE_VENDEDOR,VENDEDOR,EMPLEADO
WHERE CLIENTE_VENDEDOR.ID_CLIENTE = _ID_CLIENTE
AND PEDIDO.ID_CLIENTE_VENDEDOR = CLIENTE_VENDEDOR.ID_CLIENTE_VENDEDOR
AND VENDEDOR.ID_VENDEDOR = CLIENTE_VENDEDOR.ID_VENDEDOR
AND EMPLEADO.ID_EMPLEADO = VENDEDOR.ID_EMPLEADO
AND ACTIVE = TRUE;
END$

CREATE PROCEDURE LISTAR_PEDIDO_POR_ESTADO(
	IN _ESTADO_PEDIDO ENUM('Aceptado','Rechazado','Pendiente','Pagado'))
BEGIN
SELECT * FROM PEDIDO,CLIENTE_VENDEDOR,VENDEDOR,EMPLEADO
WHERE PEDIDO.ESTADO_PEDIDO = _ESTADO_PEDIDO
AND VENDEDOR.ID_VENDEDOR = CLIENTE_VENDEDOR.ID_VENDEDOR
AND EMPLEADO.ID_EMPLEADO = VENDEDOR.ID_EMPLEADO
AND ACTIVE = TRUE;
END$