DELIMITER $
DROP PROCEDURE IF EXISTS INSERTAR_PRODUCTO;
CREATE PROCEDURE INSERTAR_PRODUCTO(
	OUT _ID_PRODUCTO INT,
    IN _NOMBRE_PRODUCTO VARCHAR(80),
    IN _STOCK_EMPRESA INT,
    IN _STOCK_VENDEDOR INT,
    IN _PRECIO_UNITARIO FLOAT,
    IN _DESCRIPCION VARCHAR(80),
    IN _ACTIVE TINYINT(1)
    )
BEGIN
INSERT INTO PRODUCTO(NOMBRE_PRODUCTO,STOCK_EMPRESA,STOCK_VENDEDOR,PRECIO_UNITARIO,DESCRIPCION,ACTIVE)
VALUES (_NOMBRE_PRODUCTO,_STOCK_EMPRESA,_STOCK_VENDEDOR,_PRECIO_UNITARIO,_DESCRIPCION,_ACTIVE);
SET _ID_PRODUCTO = last_insert_id();
END$

DROP PROCEDURE IF EXISTS ACTUALIZAR_PRODUCTO;
CREATE PROCEDURE ACTUALIZAR_PRODUCTO(
	IN _ID_PRODUCTO INT,
    IN _NOMBRE_PRODUCTO VARCHAR(80),
    IN _STOCK_EMPRESA INT,
    IN _STOCK_VENDEDOR INT,
    IN _PRECIO_UNITARIO FLOAT,
    IN _DESCRIPCION VARCHAR(80))
BEGIN
UPDATE PRODUCTO
SET NOMBRE_PRODUCTO = _NOMBRE_PRODUCTO, STOCK_EMPRESA = _STOCK_EMPRESA, STOCK_VENDEDOR = _STOCK_VENDEDOR,
PRECIO_UNITARIO = _PRECIO_UNITARIO, DESCRIPCION = _DESCRIPCION
WHERE ID_PRODUCTO = _ID_PRODUCTO;
END$

DROP PROCEDURE IF EXISTS ELIMINAR_PRODUCTO;
CREATE PROCEDURE ELIMINAR_PRODUCTO(
	IN _ID_PRODUCTO INT)
BEGIN
UPDATE PRODUCTO
SET ACTIVE = FALSE
WHERE ID_PRODUCTO = _ID_PRODUCTO;
END$

DROP PROCEDURE IF EXISTS LISTAR_PRODUCTO_DISPONIBLE;
CREATE PROCEDURE LISTAR_PRODUCTO_DISPONIBLE()
BEGIN
SELECT * FROM PRODUCTO
WHERE STOCK_EMPRESA > 0 AND ACTIVE = TRUE;
END$
	