DELIMITER $
DROP PROCEDURE IF EXISTS INSERTAR_PROVINCIA;
CREATE PROCEDURE INSERTAR_PROVINCIA(
	OUT _ID_PROVINCIA INT,
    IN _NOMBRE_PROVINCIA VARCHAR(80),
    IN _ID_DEPARTAMENTO INT,
    IN _ACTIVE TINYINT(1))
BEGIN
INSERT INTO PROVINCIA(NOMBRE_PROVINCIA,ID_DEPARTAMENTO,ACTIVE)
VALUES (_NOMBRE_PROVINCIA,_ID_DEPARTAMENTO,_ACTIVE);
SET _ID_PROVINCIA = last_insert_id();
END$

DROP PROCEDURE IF EXISTS ACTUALIZAR_PROVINCIA;
CREATE PROCEDURE ACTUALIZAR_PROVINCIA(
	IN _ID_PROVINCIA INT,
    IN _NOMBRE_PROVINCIA VARCHAR(80),
    IN _ID_DEPARTAMENTO INT)
BEGIN
UPDATE PROVINCIA
SET NOMBRE_PROVINCIA = _NOMBRE_PROVINCIA, ID_DEPARTAMENTO = _ID_DEPARTAMENTO
WHERE ID_PROVINCIA = _ID_PROVINCIA;
END$

DROP PROCEDURE IF EXISTS ELIMINAR_PROVINCIA;
CREATE PROCEDURE ELIMINAR_PROVINCIA(
	IN _ID_PROVINCIA INT)
BEGIN
UPDATE PROVINCIA
SET ACTIVE = FALSE
WHERE ID_PROVINCIA = _ID_PROVINCIA;
END$

DROP PROCEDURE IF EXISTS LISTAR_PROVINCIA_POR_DEPARTAMENTO;
CREATE PROCEDURE LISTAR_PROVINCIA_POR_DEPARTAMENTO(
	IN _ID_DEPARTAMENTO INT)
BEGIN
SELECT * FROM PROVINCIA
INNER JOIN DEPARTAMENTO ON DEPARTAMENTO.ID_DEPARTAMENTO = _ID_DEPARTAMENTO
WHERE PROVINCIA.ACTIVE = TRUE;
END$