DROP PROCEDURE IF EXISTS INSERTAR_SOLICITUD;
DROP PROCEDURE IF EXISTS ACTUALIZAR_SOLICITUD;
DROP PROCEDURE IF EXISTS ELIMINAR_SOLICITUD;
DROP PROCEDURE IF EXISTS LISTAR_LINEAS_SOLICITUD;
DROP PROCEDURE IF EXISTS LISTAR_SOLICITUDES_POR_ESTADO;
DROP PROCEDURE IF EXISTS LISTAR_SOLICITUD;
DROP PROCEDURE IF EXISTS LISTAR_SOLICITUDES_POR_ESTADO;
DROP PROCEDURE IF EXISTS INSERTAR_LINEA_SOLICITUD;
DROP PROCEDURE IF EXISTS ACTUALIZAR_LINEA_SOLICITUD;
DROP PROCEDURE IF EXISTS BUSCAR_SOLICITUD_POR_PEDIDO;
DELIMITER $
CREATE PROCEDURE INSERTAR_SOLICITUD(
	OUT _ID_SOLICITUD INT,
    IN _ESTADO_SOLICITUD ENUM('Aceptado','Rechazado','Pendiente'),
    IN _ID_PEDIDO INT,
    IN _FECHA_REGISTRO DATE,
    IN _ID_LOGISTICO INT,
    IN _ID_FACTURADOR INT,
    IN _ACTIVE TINYINT(1))
BEGIN
INSERT INTO SOLICITUD(ESTADO_SOLICITUD,ID_PEDIDO,FECHA_REGISTRO,ID_LOGISTICO,ID_FACTURADOR,ACTIVE)
VALUES (_ESTADO_SOLICITUD,_ID_PEDIDO,_FECHA_REGISTRO,_ID_LOGISTICO,_ID_FACTURADOR,_ACTIVE);
SET _ID_SOLICITUD = last_insert_id();
END$

CREATE PROCEDURE ACTUALIZAR_SOLICITUD(
	IN _ID_SOLICITUD INT,
    IN _ESTADO_SOLICITUD ENUM('Aceptado','Rechazado','Pendiente'),
    IN _ID_PEDIDO INT,
    IN _FECHA_REGISTRO DATE,
    IN _ID_LOGISTICO INT,
    IN _ID_FACTURADOR INT)
BEGIN
UPDATE SOLICITUD
SET ESTADO_SOLICITUD = _ESTADO_SOLICITUD, ID_PEDIDO = _ID_PEDIDO,
FECHA_REGISTRO = _FECHA_REGISTRO,
ID_LOGISTICO = _ID_LOGISTICO, ID_FACTURADOR = _ID_FACTURADOR
WHERE ID_SOLICITUD = _ID_SOLICITUD;
END$

CREATE PROCEDURE ELIMINAR_SOLICITUD(
	IN _ID_SOLICITUD INT)
BEGIN
UPDATE SOLICITUD
SET ACTIVE = FALSE
WHERE ID_SOLICITUD = _ID_SOLICITUD;
END$

CREATE PROCEDURE INSERTAR_LINEA_SOLICITUD(
	OUT _ID_LINEA_SOLICITUD INT,
	IN _ID_SOLICITUD INT,
    IN _ID_LINEA_PEDIDO INT,
    IN _CANTIDAD INT,
    IN _ESTADO_SOLICITUD ENUM('Aceptado','Rechazado','Pendiente'),
    IN _ACTIVE TINYINT(1))
BEGIN
INSERT INTO LINEA_SOLICITUD(ID_SOLICITUD,ID_LINEA_PEDIDO,CANTIDAD,ESTADO_LINEA_SOLICITUD,ACTIVE)
VALUES(_ID_SOLICITUD,_ID_LINEA_PEDIDO,_CANTIDAD,_ESTADO_SOLICITUD,_ACTIVE);
SET _ID_LINEA_SOLICITUD = last_insert_id();
END$

CREATE PROCEDURE ACTUALIZAR_LINEA_SOLICITUD(
	OUT _ID_LINEA_SOLICITUD INT,
	IN _ID_SOLICITUD INT,
    IN _ID_LINEA_PEDIDO INT,
    IN _CANTIDAD INT,
    IN _ESTADO_SOLICITUD ENUM('Aceptado','Rechazado','Pendiente'))
BEGIN
UPDATE LINEA_SOLICITUD
SET ID_SOLICITUD = _ID_SOLICITUD, ID_LINEA_PEDIDO = _ID_LINEA_PEDIDO,
CANTIDAD = _CANTIDAD, ESTADO_LINEA_SOLICITUD = _ESTADO_SOLICITUD;
END$

CREATE PROCEDURE LISTAR_LINEAS_SOLICITUD(
	IN _ID_SOLICITUD INT)
BEGIN
SELECT LINEA_SOLICITUD.ID_LINEA_SOLICITUD, LINEA_SOLICITUD.ESTADO_LINEA_SOLICITUD,
LINEA_PEDIDO.CANTIDAD, LINEA_PEDIDO.CANTIDAD_A_ATENDER, LINEA_PEDIDO.ESTADO_LINEA_PEDIDO,
PRODUCTO.NOMBRE_PRODUCTO, PRODUCTO.DESCRIPCION FROM LINEA_SOLICITUD, LINEA_PEDIDO,PRODUCTO
WHERE LINEA_SOLICITUD.ID_SOLICITUD = _ID_SOLICITUD
AND LINEA_PEDIDO.ID_LINEA_PEDIDO = LINEA_SOLICITUD.ID_LINEA_PEDIDO
AND PRODUCTO.ID_PRODUCTO = LINEA_PEDIDO.ID_PRODUCTO;
END$

CREATE PROCEDURE LISTAR_SOLICITUD()
BEGIN
SELECT * FROM SOLICITUD
WHERE ACTIVE = TRUE;
END$

CREATE PROCEDURE LISTAR_SOLICITUDES_POR_ESTADO(
	IN _ESTADO_SOLICITUD ENUM('Aceptado','Rechazado','Pendiente'))
BEGIN
SELECT * FROM SOLICITUD
WHERE ACTIVE = TRUE
AND ESTADO_LINEA_SOLICITUD = _ESTADO_SOLICITUD;
END$

CREATE PROCEDURE BUSCAR_SOLICITUD_POR_PEDIDO(
	IN _ID_PEDIDO INT)
BEGIN
SELECT s.ID_SOLICITUD, s.ESTADO_SOLICITUD, s.FECHA_REGISTRO, s.ID_LOGISTICO, s.ID_FACTURADOR 
FROM SOLICITUD s, PEDIDO p
WHERE p.ID_PEDIDO = _ID_PEDIDO;
END$