SET FOREIGN_KEY_CHECKS = 0;
USE lp2;

DROP TABLE IF EXISTS DATOS_GENERALES;
CREATE TABLE DATOS_GENERALES(
	ID_DATOS_GENERALES INT PRIMARY KEY AUTO_INCREMENT,
	IGV FLOAT NOT NULL,
	SUELDO_MINIMO FLOAT NOT NULL,
    CORREO_EMPRESA VARCHAR(80) NOT NULL,
    CONTRASEÑA_EMPRESA VARCHAR(80) NOT NULL,
    FECHA DATE NOT NULL,
    PLAZO_DE_PAGO INT NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPLEADO INT,
    FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
	NOMBRE_USUARIO VARCHAR(80) NOT NULL,
    CONTRASEÑA VARCHAR(80) NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PRODUCTO VARCHAR(80) NOT NULL,
    STOCK_EMPRESA INT NOT NULL,
    STOCK_VENDEDOR INT NOT NULL,
    PRECIO_UNITARIO FLOAT NOT NULL,
    DESCRIPCION VARCHAR(80),
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS DEPARTAMENTO;
CREATE TABLE DEPARTAMENTO(
	ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_DEPARTAMENTO VARCHAR(80) NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS PROVINCIA;
CREATE TABLE PROVINCIA(
	ID_PROVINCIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PROVINCIA VARCHAR(80) NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    ACTIVE TINYINT(1) NOT NULL
)ENGINE = INNODB;

DROP TABLE IF EXISTS AREA;
CREATE TABLE AREA(
	ID_AREA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_AREA VARCHAR(80) NOT NULL,
    CODIGO_AREA INT NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS EMPLEADO;
CREATE TABLE EMPLEADO(
	ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_EMPLEADO VARCHAR(80) NOT NULL,
    APELLIDOS_EMPLEADO VARCHAR(80) NOT NULL,
    DNI_EMPLEADO VARCHAR(8) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO_EMPLEADO VARCHAR(10),
    CORREO_EMPLEADO VARCHAR(80),
    ESTADO_CIVIL ENUM('Soltero','Casado') NOT NULL,
    SUELDO FLOAT NOT NULL,
    ID_AREA INT NOT NULL,
    FOREIGN KEY(ID_AREA) REFERENCES AREA(ID_AREA),
    FECHA_INGRESO DATE NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS VENDEDOR;
CREATE TABLE VENDEDOR(
	ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPLEADO INT,
    FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    ACTIVE TINYINT(1)
)ENGINE=INNODB;

DROP TABLE IF EXISTS CLIENTE_VENDEDOR;
CREATE TABLE CLIENTE_VENDEDOR(
	ID_CLIENTE_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    ID_VENDEDOR INT,
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
)ENGINE=INNODB;

DROP TABLE IF EXISTS META_MENSUAL;
CREATE TABLE META_MENSUAL(
	ID_META_MENSUAL INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    CANTIDAD_OBJETIVO FLOAT NOT NULL,
    DESCRIPCION_META_MENSUAL VARCHAR(80),
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS OBJETIVO_VENDEDOR;
CREATE TABLE OBJETIVO_VENDEDOR(
	ID_OBJETIVO_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,    
    ID_META_MENSUAL INT NOT NULL,
    FOREIGN KEY (ID_META_MENSUAL) REFERENCES META_MENSUAL(ID_META_MENSUAL),
    MONTO FLOAT NOT NULL,
    ID_VENDEDOR INT,
    FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
    COMISION FLOAT NOT NULL,
    BONO FLOAT NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;


DROP TABLE IF EXISTS LINEA_PEDIDO;
CREATE TABLE LINEA_PEDIDO(
	ID_LINEA_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    CANTIDAD INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    ESTADO_LINEA_PEDIDO ENUM('Aceptado','Rechazado','Pendiente'),
    FECHA_ATENCION DATE NOT NULL,
    CANTIDAD_A_ATENDER INT NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    RUC VARCHAR(11) NOT NULL,
    RAZON_SOCIAL VARCHAR(80) NOT NULL,
    DIRECCION VARCHAR(80) NOT NULL,
    TELEFONO_CLIENTE VARCHAR(80),
    ID_PROVINCIA INT NOT NULL,
    FOREIGN KEY(ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA),
    CORREO_CLIENTE VARCHAR(80),
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;


DROP TABLE IF EXISTS PEDIDO;
CREATE TABLE PEDIDO(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	TOTAL_PEDIDO FLOAT NOT NULL,    
    ID_CLIENTE_VENDEDOR INT,
    FOREIGN KEY(ID_CLIENTE_VENDEDOR) REFERENCES CLIENTE_VENDEDOR(ID_CLIENTE_VENDEDOR),
    ESTADO_PEDIDO ENUM('Aceptado','Rechazado','Pendiente','Pagado') NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;


DROP TABLE IF EXISTS LINEA_SOLICITUD;
CREATE TABLE LINEA_SOLICITUD(
	ID_LINEA_SOLICITUD INT PRIMARY KEY AUTO_INCREMENT,
    ID_SOLICITUD INT NOT NULL,
    ID_LINEA_PEDIDO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY(ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD),
    FOREIGN KEY(ID_LINEA_PEDIDO) REFERENCES LINEA_PEDIDO(ID_LINEA_PEDIDO),
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS SOLICITUD;
CREATE TABLE SOLICITUD(
	ID_SOLICITUD INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION_SOLICITUD VARCHAR(80) NOT NULL,
    ESTADO_SOLICITUD ENUM('Aceptado','Rechazado','Pendiente') NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    ID_FACTURADOR INT NOT NULL,
    ID_LOGISTICO INT,
    FOREIGN KEY(ID_FACTURADOR) REFERENCES EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY(ID_LOGISTICO) REFERENCES EMPLEADO(ID_EMPLEADO),
    ACTIVE TINYINT(1) NOT NULL
)ENGINE=INNODB;