DELIMITER $
DROP PROCEDURE IF EXISTS INSERTAR_USUARIO;
CREATE PROCEDURE INSERTAR_USUARIO(	
    OUT _ID_USUARIO INT,
    IN _ID_EMPLEADO INT,
    IN _NOMBRE_USUARIO VARCHAR(80),
    IN _CONTRASEÑA VARCHAR(80),
    IN _ACTIVE TINYINT(1))
BEGIN
	INSERT INTO USUARIO(ID_EMPLEADO,NOMBRE_USUARIO,CONTRASEÑA,ACTIVE)
	VALUES(_ID_EMPLEADO,_NOMBRE_USUARIO,_CONTRASEÑA,_ACTIVE);
	SET _ID_USUARIO = last_insert_id();
END$

DROP PROCEDURE IF EXISTS ACTUALIZAR_USUARIO;
CREATE PROCEDURE ACTUALIZAR_USUARIO(
	IN _ID_USUARIO INT,
	IN _NOMBRE_USUARIO VARCHAR(80),
    IN _CONTRASEÑA VARCHAR(80)
)
BEGIN
	UPDATE USUARIO
    SET NOMBRE_USUARIO = _NOMBRE_USUARIO, CONTRASEÑA = _CONTRASEÑA
    WHERE ID_USUARIO = _ID_USUARIO;
END$

DROP PROCEDURE IF EXISTS ELIMINAR_USUARIO;
CREATE PROCEDURE ELIMINAR_USUARIO(
	IN _ID_USUARIO INT
)
BEGIN
	UPDATE USUARIO
	SET ACTIVE = false
	WHERE ID_USUARIO = _ID_USUARIO;
END$

DROP PROCEDURE IF EXISTS LISTAR_USUARIO;
CREATE PROCEDURE LISTAR_USUARIO()
BEGIN
SELECT * FROM USUARIO
INNER JOIN EMPLEADO on EMPLEADO.ID_EMPLEADO = USUARIO.ID_EMPLEADO
WHERE USUARIO.ACTIVE = TRUE;
END$