DELIMITER $
DROP PROCEDURE IF EXISTS INSERTAR_USUARIO;
DROP PROCEDURE IF EXISTS ACTUALIZAR_USUARIO;
DROP PROCEDURE IF EXISTS ELIMINAR_USUARIO;
DROP PROCEDURE IF EXISTS LISTAR_USUARIO;
DROP PROCEDURE IF EXISTS BUSCAR_AREA_POR_USUARIO;
DROP PROCEDURE IF EXISTS BUSCAR_USUARIO_POR_EMPLEADO;
CREATE PROCEDURE INSERTAR_USUARIO(	
    OUT _ID_USUARIO INT,
    IN _ID_EMPLEADO INT,
    IN _NOMBRE_USUARIO VARCHAR(80),
    IN _CONTRASEÑA VARCHAR(80),
    IN _ACTIVE TINYINT(1))
BEGIN
	INSERT INTO USUARIO(ID_EMPLEADO,NOMBRE_USUARIO,CONTRASEÑA,ACTIVE)
	VALUES(_ID_EMPLEADO,_NOMBRE_USUARIO,_CONTRASEÑA,_ACTIVE);
	SET _ID_USUARIO = last_insert_id();
END$

CREATE PROCEDURE ACTUALIZAR_USUARIO(
	IN _ID_USUARIO INT,
	IN _NOMBRE_USUARIO VARCHAR(80),
    IN _CONTRASEÑA VARCHAR(80)
)
BEGIN
	UPDATE USUARIO
    SET NOMBRE_USUARIO = _NOMBRE_USUARIO, CONTRASEÑA = _CONTRASEÑA
    WHERE ID_USUARIO = _ID_USUARIO;
END$

CREATE PROCEDURE ELIMINAR_USUARIO(
	IN _ID_USUARIO INT
)
BEGIN
	UPDATE USUARIO
	SET ACTIVE = false
	WHERE ID_USUARIO = _ID_USUARIO;
END$


CREATE PROCEDURE LISTAR_USUARIO()
BEGIN
SELECT * FROM USUARIO
INNER JOIN EMPLEADO on EMPLEADO.ID_EMPLEADO = USUARIO.ID_EMPLEADO
WHERE USUARIO.ACTIVE = TRUE;
END$

CREATE PROCEDURE BUSCAR_AREA_POR_USUARIO(
        IN	_NOMBRE_USUARIO VARCHAR(80))
BEGIN
SELECT NOMBRE_AREA FROM USUARIO,EMPLEADO,AREA
WHERE USUARIO.NOMBRE_USUARIO = _NOMBRE_USUARIO
AND EMPLEADO.ID_EMPLEADO = USUARIO.ID_USUARIO
AND AREA.ID_AREA = EMPLEADO.ID_AREA;
END$

CREATE PROCEDURE BUSCAR_USUARIO_POR_EMPLEADO(
	IN _DNI_EMPLEADO VARCHAR(8))
BEGIN
SELECT * FROM USUARIO,EMPLEADO
WHERE EMPLEADO.DNI_EMPLEADO = _DNI_EMPLEADO
AND USUARIO.ID_EMPLEADO = EMPLEADO.ID_EMPLEADO;
END$