DROP PROCEDURE IF EXISTS INSERTAR_VENDEDOR;
DROP PROCEDURE IF EXISTS ELIMINAR_VENDEDOR;
DROP PROCEDURE IF EXISTS LISTAR_PEDIDOS_POR_VENDEDOR_POR_RANGO_DE_FECHAS;
DELIMITER $
CREATE PROCEDURE INSERTAR_VENDEDOR(
	OUT _ID_VENDEDOR INT,
    IN _ID_EMPLEADO INT
)
BEGIN
INSERT INTO VENDEDOR(ID_EMPLEADO)
VALUES (_ID_EMPLEADO);
SET _ID_VENDEDOR = last_insert_id();
END$

CREATE PROCEDURE ELIMINAR_VENDEDOR(
	IN _ID_VENDEDOR INT
)
BEGIN
UPDATE VENDEDOR, EMPLEADO
SET VENDEDOR.ACTIVE = FALSE, EMPLEADO.ACTIVE = FALSE
WHERE ID_VENDEDOR = _ID_VENDEDOR AND VENDEDOR.ID_EMPLEADO = EMPLEADO.ID_EMPLEADO;
END$

CREATE PROCEDURE LISTAR_PEDIDOS_POR_VENDEDOR_POR_RANGO_DE_FECHAS(
	IN _FECHA_INI DATE,
    IN _FECHA_FIN DATE,
    IN _ID_VENDEDOR INT)
BEGIN
SELECT * FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE_VENDEDOR.ID_CLIENTE_VENDEDOR = PEDIDO.ID_CLIENTE_VENDEDOR
WHERE CLIENTE_VENDEDOR.ID_VENDEDOR = _ID_VENDEDOR AND PEDIDO.FECHA_REGISTRO BETWEEN _FECHA_INI AND _FECHA_FIN;
END$
