DROP PROCEDURE IF EXISTS INSERTAR_VENDEDOR;
DROP PROCEDURE IF EXISTS ELIMINAR_VENDEDOR;
DELIMITER $
CREATE PROCEDURE INSERTAR_VENDEDOR(
	OUT _ID_VENDEDOR INT,
    IN _ID_EMPLEADO INT
)
BEGIN
INSERT INTO VENDEDOR(ID_EMPLEADO)
VALUES (_ID_EMPLEADO);
SET _ID_VENDEDOR = last_insert_id();
END$

CREATE PROCEDURE ELIMINAR_VENDEDOR(
	IN _ID_VENDEDOR INT
)
BEGIN
UPDATE VENDEDOR, EMPLEADO
SET VENDEDOR.ACTIVE = FALSE, EMPLEADO.ACTIVE = FALSE
WHERE ID_VENDEDOR = _ID_VENDEDOR AND VENDEDOR.ID_EMPLEADO = EMPLEADO.ID_EMPLEADO;
END$

